app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import beranda, visimisi, strorg, alumni, detailalumni, agenda, pengumuman, loker,  donasi, detailagenda, detailpengumuman, detailloker, informasi
from .views import register, sigin, logout_user, verification
from .views import ajukandata, postajukandata, homeuser, updatedata, postupdatedata, bincangalumni, addmessage, reply
from .views import header
from .views import dataalumni, deletealumni, postdeletealumni, homeadmin, footer, verifikasi, tolakverif, posttolakverif, addadmin, dataadmin, deleteadmin, postdeleteadmin
from .views import dataagenda, addagenda, postagenda, deleteagenda, postdeleteagenda, updateagenda, postupdateagenda
from .views import datapengumuman, addpengumuman, postpengumuman, updatepengumuman, postupdatepengumuman, deletepengumuman, postdeletepengumuman 
from .views import dataloker, addloker, postloker, updateloker, postupdateloker, deleteloker, postdeleteloker
# addagenda, addpengumuman, addloker

urlpatterns = [
    #Landing Page
    path('',beranda,name="beranda"),
    path('visimisi',visimisi,name='visimisi'),
    path('strorg',strorg,name='strorg'),
    path('alumni',alumni,name='alumni'),
    path('detailalumni/<str:nim>',detailalumni,name='detailalumni'),
    path('agenda',agenda,name='agenda'),
    path('detailagenda/<str:idagenda>',detailagenda,name='detailagenda'),
    path('pengumuman/',pengumuman,name='pengumuman'),
    path('detailpengumuman/<str:idpengumuman>',detailpengumuman,name='detailpengumuman'),
    path('loker/',loker,name='loker'),
    path('detailloker/<str:idloker>',detailloker,name='detailloker'),
    path('donasi',donasi,name='donasi'),
    path('informasi',informasi,name='informasi'),
    
    #Authentication
    path('register/', register, name='register'),
    path('verification/<uidb64>/<token>/', verification, name='verification'),
    path('login/', sigin, name='login'),
    path('logout/', logout_user, name='logout'),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="auth/resetpassword.html"), name='password_reset'),
    path('reset_password/done/', auth_views.PasswordResetDoneView.as_view(template_name="auth/resetpasswordmessage.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="auth/resetpasswordconfirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name="auth/resetpassworddone.html"), name='password_reset_complete'),

    
    #Template
    path('footer',footer,name='footer'),
    path('header',header,name='header'),
    
    #User
    path('ajukandata',ajukandata,name='ajukandata'),
    path('postajukandata',postajukandata,name='postajukandata'),
    path('homeuser',homeuser,name='homeuser'),
    path('updatedata/<str:nim>',updatedata,name='updatedata'),
    path('postupdatedata',postupdatedata,name='postupdatedata'),
    path('bincangalumni',bincangalumni,name='bincangalumni'),
    path('addmessage',addmessage,name='addmessage'),
    path('reply/<int:id>',reply,name='reply'),
    # path('postreply',postreply,name='postreply'),
    
    #Admin
    path('dataalumni/',dataalumni,name='dataalumni'),
    path('deletealumni/<str:nim>', deletealumni, name='deletealumni'),
    path('postdeletealumni/<str:nim>',postdeletealumni,name='postdeletealumni'),
    path('homeadmin',homeadmin,name='homeadmin'),
    path('verifikasi',verifikasi,name='verifikasi'),
    path('tolakverif/<str:nim>',tolakverif,name='tolakverif'),
    path('posttolakverif/<str:nim>',posttolakverif,name='posttolakverif'),
    path('addadmin',addadmin,name='addadmin'),
    path('deleteadmin/<str:id>',deleteadmin,name='deleteadmin'),
    path('postdeleteadmin/<str:id>',postdeleteadmin,name='postdeleteadmin'),
    
    # path('postadmin',postadmin,name='postadmin'),
    path('dataadmin',dataadmin,name='dataadmin'),
    #Admin => CRUD Agenda
    path('dataagenda',dataagenda,name='dataagenda'),
    path('addagenda',addagenda,name='addagenda'),
    path('postagenda',postagenda,name='postagenda'),
    path('deleteagenda/<str:idagenda>',deleteagenda,name='deleteagenda'),
    path('postdeleteagenda/<str:idagenda>',postdeleteagenda,name='postdeleteagenda'),
    path('updateagenda/<str:idagenda>',updateagenda,name='updateagenda'),
    path('postupdateagenda',postupdateagenda,name='postupdateagenda'),
    #Admin => CRUD Pengumuman
    path('datapengumuman',datapengumuman,name='datapengumuman'),
    path('addpengumuman',addpengumuman,name='addpengumuman'),
    path('postpengumuman',postpengumuman,name='postpengumuman'),
    path('updatepengumuman/<str:idpengumuman>',updatepengumuman,name='updatepengumuman'),
    path('postupdatepengumuman',postupdatepengumuman,name='postupdatepengumuman'),
    path('deletepengumuman/<str:idpengumuman>',deletepengumuman,name='deletepengumuman'),
    path('postdeletepengumuman/<str:idpengumuman>',postdeletepengumuman,name='postdeletepengumuman'),
    #Admin => CRUD LOKER
    path('dataloker',dataloker,name='dataloker'),
    path('addloker',addloker,name='addloker'),
    path('postloker',postloker,name='postloker'),
    path('updateloker/<str:idloker>',updateloker,name='updateloker'),
    path('postupdateloker',postupdateloker,name='postupdateloker'),
    path('deleteloker/<str:idloker>',deleteloker,name='deleteloker'),
    path('postdeleteloker/<str:idloker>',postdeleteloker,name='postdeleteloker')
    
    
    
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
# from allauth.account.views import LoginView, LogoutView, SignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
    # path('accounts/', include('allauth.urls')),
]

app/models.py
from enum import Enum
import os
from django.db import models
from django.contrib.auth.models import User

from project import settings


class DataAlumni(models.Model):
    nim = models.CharField(primary_key=True, max_length=20)
    nama = models.CharField(max_length=255)
    alamat = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    nohp = models.CharField(max_length=255)
    thnlulus = models.IntegerField()
    prodi = models.CharField(max_length=255)
    instansi = models.CharField(max_length=255)
    jabatan = models.CharField(max_length=255)
    gambar = models.ImageField(upload_to='static/assets/images', blank=True, null=True)
    grup = models.CharField(max_length=255)
    linkedin = models.CharField(max_length=255)
    instagram = models.CharField(max_length=255)
    facebook = models.CharField(max_length=255)
    status = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def delete(self, *args, **kwargs):
        # hapus foto yang terkait dengan instance Alumni saat dihapus
        if self.gambar:
            os.remove(self.gambar.path)
        super().delete(*args, **kwargs)


class Agenda(models.Model):
    idagenda = models.AutoField(primary_key=True)
    namaagenda = models.CharField(max_length=255)
    dateagenda = models.DateField()
    deskripsiagenda = models.CharField(max_length=500)
    
class Pengumuman(models.Model):
    idpengumuman = models.AutoField(primary_key=True)
    namapengumuman = models.CharField(max_length=255)
    datepengumuman = models.DateField()
    deskripsipengumuman = models.CharField(max_length=500)
    filepengumuman = models.FileField(upload_to='static/assets/file', blank=True, null=True)
    
    def delete(self, *args, **kwargs):
        # hapus file yang terkait dengan Pengumuman saat dihapus
        if self.filepengumuman:
            os.remove(self.filepengumuman.path)
        super().delete(*args, **kwargs)

class Loker(models.Model):
    idloker = models.AutoField(primary_key=True)
    dateloker = models.DateField()
    namaloker = models.CharField(max_length=255)
    instansi = models.CharField(max_length=255)
    fileloker = models.FileField(upload_to='static/assets/file', blank=True, null=True)
    
    def delete(self, *args, **kwargs):
        # hapus file yang terkait dengan Loker saat dihapus
        if self.fileloker:
            os.remove(self.fileloker.path)
        super().delete(*args, **kwargs)

class BincangAlumni(models.Model):
    id  = models.AutoField(primary_key=True)
    pesan = models.CharField(max_length=250)
    date = models.DateField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class Reply(models.Model):
    message = models.ForeignKey(BincangAlumni, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    reply = models.CharField(max_length=250)
    date_reply = models.DateField()

    def __str__(self):
        return f'{self.user.username} - {self.message}'
    
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='static/assets/images/profile', blank=True, null=True)

    def __str__(self):
        return self.user.username
    

templates/user/ajukandata.html
{% extends 'layout/baseuser.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if messages %}
    {% for message in messages %}
    <p class="alert alert-danger alert-dismissible fade show" role="alert">{{ message }}</p>
    {% endfor %}
    {% endif %}
    <div class="card">
        <div class="card-body">
            <form action="{% url 'postajukandata' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <h1 class="font-weight-bold text-primary">Form Ajukan Data Alumni</h1> <br>
                <div class="form-group">
                    <p class="">NIM</p>
                    <input class="form-control" type="text" name="nim" maxlength="20" required>
                </div>
                <div class="form-group">
                    <p>Nama</p>
                    <input class="form-control" type="text" name="nama" maxlength="255" value="{{ user.first_name }}" required>
                </div>
                <div class="form-group">
                    <p>Alamat</p>
                    <input class="form-control" type="text" name="alamat" maxlength="255" required>
                </div>
                <div class="form-group">
                    <p>Email</p>
                    <input class="form-control" type="text" name="email" maxlength="255" value="{{ user.email }}" required>
                </div>
                <div class="form-group">
                    <p>No Hp</p>
                    <input class="form-control" type="text" name="nohp" required>
                </div>
                <div class="form-group">
                    <p>Tahun Lulus</p>
                    <input class="form-control" type="number" name="thnlulus" required>
                </div>
                <div class="form-group">
                    <p>Prodi</p>
                    <input class="form-control" type="text" name="prodi" maxlength="255" required>
                </div>
                <div class="form-group">
                    <p>Instansi</p>
                    <input class="form-control" type="text" name="instansi" maxlength="255">
                </div>
                <div class="form-group">
                    <p>Jabatan</p>
                    <input class="form-control" type="text" name="jabatan" maxlength="255">
                </div>
                <div class="form-group">
                    <p>Grup Whatsapp yang di ikuti</p>
                    <input class="form-control" type="text" name="grup" maxlength="255">
                </div>
                <div class="form-group">
                    <p>Tautan akun Linkedin (Optional)</p>
                    <input class="form-control" type="text" name="linkedin" maxlength="255" placeholder="https://www.linkedin.com/.....">
                </div>
                <div class="form-group">
                    <p>Tautan akun Instagram (Optional)</p>
                    <input class="form-control" type="text" name="instagram" maxlength="255" placeholder="https://www.instagram.com/....">
                </div>
                <div class="form-group">
                    <p>Tautan akun Facebook (Optional)</p>
                    <input class="form-control" type="text" name="facebook" maxlength="255" placeholder="https://www.facebook.com/....">
                </div>
                <div class="form-group">
                    <p>Gambar</p>
                    <input style="width: fit-content;" type="file" alt="" name="gambar" required>
                </div>
                <button class="btn btn-success" type="submit">SUBMIT</button>
                <a class="btn btn-warning " href="{% url 'dataalumni' %}">KEMBALI</a>
            </form>
        </div>
    </div>
</body>
</html>

{% endblock %}

templates/user/bincangalumni.html
{% extends 'layout/baseuser.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bincang Alumni</title>
    <style>
        h5:before,
        h5:after {
            content: "\00a0\00a0\00a0\00a0\00a0\00a0\00a0\00a0\00a0\00a0\00a0\00a0\00a0\00a0\00a0\00a0\00a0\00a0\00a0\00a0";
            text-decoration: line-through;
            margin: auto 0.5em;
        }
        .message-box {
            border: 1px solid #ccc;
            padding: 10px;
            /* margin: 5px; */
            background-color: royalblue;
            border-radius: 5px;
            margin-bottom: 10px;
        }
        .replies {
            display: none;
            list-style: none;
            padding: 0;
        }

        .show-replies {
            display: block;
        }

        .reply-box {
            border: 1px solid rgb(255, 255, 255);
            padding: 10px;
            margin-bottom: 10px;
            background-color: rgb(52, 83, 176);
        }

        @media (max-width: 768px) {
            h5:before,
            h5:after {
            content: "\00a0\00a0\00a0\00a0\00a0\00a0";
            text-decoration: line-through;
            margin: auto 0.2em;
            text-align: center;
            }
            .message-box {
                margin-left: 0%;
            }
            
        }
    </style>
</head>
<body>
    {% if messages %}
        {% for message in messages %}
            <p class="alert alert-success alert-dismissible fade show" role="alert">{{ message }}</p>
        {% endfor %}
    {% endif %}
    <div class="card">
        <div class="card-body">
            <form action="{% url 'addmessage' %}" method="POST">
                {% csrf_token %}
                <h1 class="font-weight-bold text-primary">Forum Bincang Alumni</h1>
                <p>Selamat datang di Forum Bincang Alumni. Disini anda bisa mengirimkan pertanyaan atau sekedar berinteraksi dengan alumni lainnya.
                    Mohon tidak mengirimkan pesan yang mengandung unsur SARA atau hal-hal negatif lainnya.</p>
                <div class="form-group">
                    <textarea class="form-control" name="pesan" rows="5" placeholder="Tuliskan Pesan Anda Disini"></textarea>
                </div>
                <button style="float: right;" class="btn btn-outline-info" type="submit"><i class="fas fa-paper-plane"></i> Send</button>
            </form>
        </div>
        <div class="card-body">
              <h5 class="text-center">Mulailah untuk berinteraksi dengan alumni yang lain </h5> <br>
              <ul>
                  {% for message in datapesan %}
                  <div class="message-box">
                    <p style="float: right; color: #faff72;">{{message.date|date:'d M Y'}}</p>
                    <p style="color: #faff72;"> {{ message.user.first_name }}</p> 
                    <p style="color: white;">{{ message.pesan }}</p>
                    <a href="#" class="reply-button" data-formid="{{ message.id }}" style="color: black;"><i class="fas fa-reply"></i> Reply</a>
                    <a href="#" class="toggle-replies" style="color: black; float: right;">Lihat Balasan <i class="fas fa-angle-down"></i></a>
                    <form id="reply-form-{{ message.id }}" action="{% url 'reply' message.id %}" method="POST" style="display: none;">
                        {% csrf_token %}
                        <div class="form-group"> <br>
                           <textarea class="form-control" name="reply" rows="2" placeholder="Balas Pesan"></textarea>
                        </div>
                        <button type="submit" class="btn btn-info"><i class="fas fa-paper-plane"></i> Send</button>
                     </form>

                     <!-- Tambahkan daftar balasan dengan class "replies" -->
                     <ul class="replies">
                         {% for reply in message.reply_set.all %}
                        <br>
                        <li class="reply-box">
                            <p style="color: #faff72; float: right;">{{ reply.date_reply|date:'d M Y'}}</p>
                            <p style="color: #faff72;">{{ reply.user.first_name }}</p> 
                            <p style="color: white;">{{ reply.reply }}</p>
                        </li>
                        {% endfor %}
                    </ul>
                  </div>
                {% endfor %}
              </ul>
          </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function() {
            // Mendaftarkan event click pada setiap tombol "Reply"
            $('.reply-button').click(function(e) {
                e.preventDefault();
                // Mendapatkan id form yang sesuai
                var formId = $(this).data('formid');
                // Menampilkan atau menyembunyikan form berdasarkan id
                $('#reply-form-' + formId).toggle();
            });
        });
        // Tambahkan JavaScript untuk menangani tampilan balasan
        document.addEventListener("DOMContentLoaded", function () {
            const toggleButtons = document.querySelectorAll(".toggle-replies");
            toggleButtons.forEach((button) => {
                button.addEventListener("click", function (e) {
                    e.preventDefault(); // Mencegah tautan mengarahkan Anda ke atas halaman
                    const replies = this.parentElement.querySelector(".replies");
                    replies.classList.toggle("show-replies");
                });
            });
        });


    </script>
</body>
</html>

{% endblock %}

templates/user/home.html
{% extends 'layout/baseuser.html' %}
{% block content %}
    {% if messages %}
        {% for message in messages %}
            <p class="alert alert-warning alert-dismissible fade show" role="alert">{{ message }}</p>
        {% endfor %}
    {% endif %}
    <h1 class="font-weight-bold text-primary mb-3">Selamat Datang, {{ user.first_name }}</h1>
    <div class="container">
        <div class="row">
            <div class="col-md-3" style="margin-bottom: 5%;">
                {% for data in user_data %}
                <div class="form-group">
                    <img style="width: 200px;" src="{{ data.gambar }}" alt="">
                </div>
                <a class="btn btn-outline-info" href="{% url 'updatedata' data.nim %}"><i class="fas fa-pencil-alt"></i> Update Data</a>
                {% endfor %}
            </div>
            <div class="col-md-9">
                <table class="table table-striped">
                    <tbody class="font-weight-bold text-black-50">
                        {% for data in user_data %}
                            <tr>
                                <th>NIM</th>
                                <td>{{ data.nim }}</td>
                            </tr>
                            <tr>
                                <th>Nama</th>
                                <td>{{ data.nama }}</td>
                            </tr>
                            <tr>
                                <th>Alamat</th>
                                <td>{{ data.alamat }}</td>
                            </tr>
                            <tr>
                                <th>Email</th>
                                <td>{{ data.email }}</td>
                            </tr>
                            <tr>
                                <th>No HP</th>
                                <td>{{ data.nohp }}</td>
                            </tr>
                            <tr>
                                <th>Prodi</th>
                                <td>{{ data.prodi }}</td>
                            </tr>
                            <tr>
                                <th>Instansi</th>
                                <td>{{ data.instansi }}</td>
                            </tr>
                            <tr>
                                <th>Jabatan</th>
                                <td>{{ data.jabatan }}</td>
                            </tr>
                            <tr>
                                <th>Akun Linkedin</th>
                                <td><a href="{{ data.linkedin }}">{{ data.linkedin }}</a></td>
                            </tr>
                            <tr>
                                <th>Akun Linkedin</th>
                                <td><a href="{{ data.instagram }}">{{ data.instagram }}</a></td>
                            </tr>
                            <tr>
                                <th>Akun Linkedin</th>
                                <td><a href="{{ data.facebook }}">{{ data.facebook }}</a></td>
                            </tr>
                            <tr>
                                <th>Grup Whatsapp yang di ikuti</th>
                                <td>{{ data.grup }}</td>
                            </tr>
                            <tr class="bg bg-success">
                                <th>Status</th>
                                <td>{% if data.status %}Diverifikasi{% else %}Belum diverifikasi{% endif %}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/profile.html
{% extends 'layout/baseuser.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="card">
        <div class="card-body">
            <form action="{% url 'addprofileimage' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <h1 class="font-weight-bold text-primary">Profile User</h1> <br>
                <div class="form-group">
                    <p>Nama : {{ user.first_name }}</p>
                </div>
                <div class="form-group">
                    <p>Username : {{ user.username }}</p>
                </div>
                {% for image in profileimage %}
                <div class="form-group">
                    <img src="{{ image.image.url }}" alt="">
                </div>
                {% endfor %}
                <!-- Profile Image -->
                <div class="form-group">
                    <p>File Terkait</p>
                    <input style="width: fit-content;" type="file" alt="" name="image" required>
                </div>
                <button class="btn btn-success" type="submit">SUBMIT</button>
            </form>
        </div>
    </div>
</body>
</html>
{% endblock %}

templates/user/reply.html
{% extends 'layout/baseuser.html' %} {% block content %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <div class="message-box">
      <strong>{{ datapesan.user.username }}:</strong> {{ datapesan.pesan }}
    </div>

    <!-- Form untuk reply -->
    <form method="post" action="{% url 'postreply' %}">
      {% csrf_token %}
      <input type="hidden" name="id_pesan" value="{{ datapesan.id }}" />
      <textarea name="pesan_reply" placeholder="Balas pesan..." rows="3"></textarea>
      <button type="submit">Kirim Reply</button>
    </form>

    <!-- Menampilkan reply -->
    {% for reply in replies %}
    <div class="reply-box">
      <strong>{{ reply.user.username }}:</strong> {{ reply.pesan_reply }}
    </div>
    {% endfor %}
  </body>
</html>
{% endblock %}

templates/user/updatedata.html
{% extends 'layout/baseuser.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if messages %}
    {% for message in messages %}
    <p class="alert alert-danger alert-dismissible fade show" role="alert">{{ message }}</p>
    {% endfor %}
    {% endif %}
    <div class="card">
        <div class="card-body">
            <form action="{% url 'postupdatedata' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <h1 class="font-weight-bold text-primary">Form Update Data Alumni</h1> <br>
                <div class="form-group">
                    <p class="">NIM</p>
                    <input class="form-control" type="text" name="nim" maxlength="20" value="{{user_data.nim}}" required>
                </div>
                <div class="form-group">
                    <p>Nama</p>
                    <input class="form-control" type="text" name="nama" maxlength="255" value="{{user_data.nama}}" required>
                </div>
                <div class="form-group">
                    <p>Alamat</p>
                    <input class="form-control" type="text" name="alamat" maxlength="255" value="{{user_data.alamat}}" required>
                </div>
                <div class="form-group">
                    <p>Email</p>
                    <input class="form-control" type="text" name="email" maxlength="255" value="{{user_data.email}}" required>
                </div>
                <div class="form-group">
                    <p>No Hp</p>
                    <input class="form-control" type="text" name="nohp" value="{{user_data.nohp}}" required>
                </div>
                <div class="form-group">
                    <p>Tahun Lulus</p>
                    <input class="form-control" type="number" name="thnlulus" value="{{user_data.thnlulus}}" required>
                </div>
                <div class="form-group">
                    <p>Prodi</p>
                    <input class="form-control" type="text" name="prodi" maxlength="255" value="{{user_data.prodi}}" required>
                </div>
                <div class="form-group">
                    <p>Instansi</p>
                    <input class="form-control" type="text" name="instansi" maxlength="255" value="{{user_data.instansi}}" required>
                </div>
                <div class="form-group">
                    <p>Jabatan</p>
                    <input class="form-control" type="text" name="jabatan" maxlength="255" value="{{user_data.jabatan}}" required>
                </div>
                <div class="form-group">
                    <p>Tautan akun Linkedin (Optional)</p>
                    <input class="form-control" type="text" name="linkedin" maxlength="255" value="{{user_data.linkedin}}">
                </div>
                <div class="form-group">
                    <p>Tautan akun Instagram (Optional)</p>
                    <input class="form-control" type="text" name="instagram" maxlength="255" value="{{user_data.instagram}}">
                </div>
                <div class="form-group">
                    <p>Tautan akun Linkedin (Optional)</p>
                    <input class="form-control" type="text" name="facebook" maxlength="255" value="{{user_data.facebook}}">
                </div>
                <div class="form-group">
                    <p>Grup Whatsapp yang di ikuti</p>
                    <input class="form-control" type="text" name="grup" maxlength="255" value="{{user_data.grup}}">
                </div>
                <div class="form-group">
                    <p>Gambar</p>
                    <img src="{{user_data.gambar.url}}" style="width: 200px;" alt="">
                    <input style="width: fit-content;" type="file" alt="" name="gambar">
                </div>
                <button class="btn btn-success" type="submit">SUBMIT</button>
                <a class="btn btn-warning " href="{% url 'homeuser' %}">KEMBALI</a>
            </form>
        </div>
    </div>
</body>
</html>

{% endblock %}